exports.index = require("./index_handler.js")
exports.login = require("./login_handler.js")
exports.submit = require("./submit_handler.js")
exports.score = require("./score_handler.js")
exports.user = require("./user_handler.js")
exports.gameswitch = require("./gameswitch_handler.js")
exports.rank = require("./rank_handler.js")
exports.backdoor= require("./backdoor_handler.js")
